/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 test1.glb --transform 
Files: test1.glb [11.09KB] > C:\Users\piotr\Downloads\diamond-rapier-merge1\public\test1-transformed.glb [1.94KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/test1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Diamond_1_0001.geometry} material={materials['gems_001.001']} />
    </group>
  )
}

useGLTF.preload('/test1-transformed.glb')
